version: "3.8"

services:
  postgres:
    image: postgres:14.2
    container_name: rfb_postgres
    restart: always
    environment:
      POSTGRES_USER: rfb_user
      POSTGRES_PASSWORD: rfb_password
      POSTGRES_DB: Dados_RFB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: rfb_adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata: